// <auto-generated />
using System;
using BlazorAppTest.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAppTest.EntityFramework.Migrations
{
    [DbContext(typeof(GameManagementDbContext))]
    [Migration("20240503043837_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlazorAppTest.Entites.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Classes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("594e6962-c855-488b-906e-c54e0b469153"),
                            Classes = "AA",
                            DateCreated = new DateTime(2024, 5, 3, 12, 38, 36, 376, DateTimeKind.Local).AddTicks(186),
                            Level = 1,
                            NickName = "A",
                            PlayerId = new Guid("190a9b07-fe75-4c33-94e8-060c0c314b7e")
                        },
                        new
                        {
                            Id = new Guid("56326a91-1aa7-4c9e-8f97-1aaffb588017"),
                            Classes = "BB",
                            DateCreated = new DateTime(2024, 5, 3, 12, 38, 36, 376, DateTimeKind.Local).AddTicks(330),
                            Level = 2,
                            NickName = "B",
                            PlayerId = new Guid("190a9b07-fe75-4c33-94e8-060c0c314b7e")
                        },
                        new
                        {
                            Id = new Guid("2ba6cf0c-57ba-4a4f-854a-6560e49e8a36"),
                            Classes = "CC",
                            DateCreated = new DateTime(2024, 5, 3, 12, 38, 36, 376, DateTimeKind.Local).AddTicks(346),
                            Level = 3,
                            NickName = "C",
                            PlayerId = new Guid("24ead4b9-ceac-41c4-adae-f783e882670b")
                        },
                        new
                        {
                            Id = new Guid("7f3fb197-efa8-4797-bda0-91e1845a4988"),
                            Classes = "DD",
                            DateCreated = new DateTime(2024, 5, 3, 12, 38, 36, 376, DateTimeKind.Local).AddTicks(348),
                            Level = 4,
                            NickName = "D",
                            PlayerId = new Guid("24ead4b9-ceac-41c4-adae-f783e882670b")
                        });
                });

            modelBuilder.Entity("BlazorAppTest.Entites.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("190a9b07-fe75-4c33-94e8-060c0c314b7e"),
                            Account = "1",
                            AccountType = "Free",
                            DateCreated = new DateTime(2024, 5, 3, 12, 38, 36, 375, DateTimeKind.Local).AddTicks(8954)
                        },
                        new
                        {
                            Id = new Guid("24ead4b9-ceac-41c4-adae-f783e882670b"),
                            Account = "2",
                            AccountType = "DeFree",
                            DateCreated = new DateTime(2024, 5, 3, 12, 38, 36, 375, DateTimeKind.Local).AddTicks(9129)
                        });
                });

            modelBuilder.Entity("BlazorAppTest.Entites.Character", b =>
                {
                    b.HasOne("BlazorAppTest.Entites.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BlazorAppTest.Entites.Player", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
