[package]
name = "tanvity-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.90", features = ["backtrace"] }
jieba-rs = "0.7.0"
tantivy = "0.22.0"
tantivy-jieba = "0.11.0"
tempfile = "3.13.0"
